defaults:
  - encoding@encoding
  - bpe_tokenizer@bpe_tokenizer
  - optimizer: adamw
  - criterion: cross_entropy
  - hardware: local
  - _self_

dataset:
  context_window: 1_024

train:
  data_path: ${encoding.save_path}/train/train.npy
  loader:
    batch_size: 64
    shuffle: True

val:
  data_path: ${encoding.save_path}/val/val.npy
  loader:
    batch_size: 64
    shuffle: False

model:
  epochs: 10
  vocab_size: ${bpe_tokenizer.vocab_size}
  d_model: 384
  n_layers: 6
  n_heads: 6
  dropout: 0.1
  bias: true
  tie_weights: true
  mlp_hidden_dim: 1_536

checkpoint:
  enabled: true
  dir: checkpoints
  checkpoint_interval: 5
  save_best: true
  save_latest: true
  resume_path: null

mlflow:
  tracking_uri: databricks
  experiment_name: ${oc.env:EXPERIMENT_NAME}
  log_model: true
  checkpoint_interval: 5
