defaults:
  - encoding

dataset:
  context_window: 2048

train:
  data_path: ${encoding.save_path}/train/train.npy
  loader:
    batch_size: 64
    shuffle: True

val:
  data_path: ${encoding.save_path}/val/val.npy
  loader:
    batch_size: 32
    shuffle: False

model:
