defaults:
  - encoding
  - bpe_tokenizer
  - optimizer: adamw
  - criterion: cross_entropy
  - hardware: local
  - _self_

dataset:
  context_window: 2_048

train:
  data_path: ${encoding.save_path}/train/train.npy
  loader:
    batch_size: 64
    shuffle: True

val:
  data_path: ${encoding.save_path}/val/val.npy
  loader:
    batch_size: 32
    shuffle: False

model:
  epochs: 100
  vocab_size: ${bpe_tokenizer.vocab_size}
